### ISSUE TITLE
405 -> 404

### ISSUE THREAD

**Issue by aheckmann** [koajs/trie-router#13]
A request made to a route that has not been defined is returning a 405 instead of 404.

``` js
it('missing route should 404', function(done) {
  app.get('/trailing-slash/', function*() {
    this.status = 204
  })

  request(server)
  .get('/trailing-slash')
  .expect(404, done)  // Error: expected 404 "Not Found", got 405 "Method Not Allowed"
});
```

If the case was that `/trailing-slash` was defined but not for a `GET` then a 405 would make sense.

**Comment by nervgh** [comment]
It looks like the issue still exists.

I'm not sure where we need fix that error (trie-router or routington) but
Could we do something simple before parsing url? For example
```js
url = url.replace(/\/$/, '')
```

**Comment by nervgh** [comment]
@jonathanong what do you think about it? :arrow_up:

**Comment by jonathanong** [comment]
i think it needs to be an option. some people treat trailing slashes differently.

**Comment by jonathanong** [comment]
yes, i think it's a routington thing

**Comment by nervgh** [comment]
I'm closing this issue because I've added [the note](https://github.com/koajs/trie-router#notes) about this behavior into docs. I think one of the possible solutions is to add [koa-no-trailing-slash](https://github.com/tssm/koa-no-trailing-slash) middleware to the top of the middleware queue.
