### ISSUE TITLE
Should not throw error for malformed URL

### ISSUE THREAD

**Issue by th507** [koajs/trie-router#19]
`routington` throws error if it fails to parse URL with `decodeURIComponent()`.

This could cause some problem when using w/ trie-router + Koa.

For example, we could create a simple server and then request for URL `/%`. Then this error occurs:

```
Possibly Unhandled Rejection at: Promise
Promise { <rejected> [NotFoundError: malformed url: /%] } 
reason:  [NotFoundError: malformed url: /%]
```

Since it throws an error explicitly, we could not gather this kind of error w/ Koa's `app.on("error")` or middleware.

I think rather than making changes for `routington`, we could consider catching the assertion error in trie-router. Because trie-router is restricted to a narrower use case (for Koa only).

**Comment by tejasmanohar** [comment]
cc8b7f7c39faacc52767e0d29a39212e5b0805a6
