### ISSUE TITLE
Do you have any plans for supporting koa@2 and make using more convenient?

### ISSUE THREAD

**Issue by nervgh** [koajs/trie-router#34]
Hi.

Trie-router is the official router and I think we could give second breath to it.

### Requirements
1. It should works with node 7.x.x and higher
2. It should support only koa@2 and higher
3. It should be mountable
4. It should be powerful as it is now

### API
+ Instantiation should requires `new` operator (like Koa@2)
    ```js
    let router = new Router();
    ```
+ Routers could be define like
    ```js
    router[use|get|post|put|del|patch]([path], [...middleware]);
    ```
    + where **path** & **middleware** both optional but it requires at least one of them
    + **path** is `{String|{Array<String>}`
    + **middleware** is `{Function|AsyncFunction|Array<[Function|AsyncFunction]>}`

+ Router should implements `router.middleware()` like `koa.middleware()` for mounting (composing)
+ `ctx.params` like https://github.com/koajs/trie-router/tree/1.1.0#thisparams
+ https://github.com/koajs/trie-router/tree/1.1.0#features

What do you think about it?

**Comment by nervgh** [comment]
@jonathanong 

I refactored trie-router for support of koa@2. Also I updated dependencies, tests and documentation.
I pushed my changes in [next](https://github.com/koajs/trie-router/tree/next) branch.

I think if koa@2 uses async/await syntax then we can [restrict node version](https://github.com/koajs/trie-router/blob/next/package.json#L14) and use benefits of ECMAScript 2015 & ECMAScript 2016 standards.

If you approve my changes, please, tag them and release.
If you have another vision about trie-router, please, let me know.

---

What still need to do (ordered by priority):
- router.use() method
- path & middleware both optional but it requires at least one of them

**Comment by jonathanong** [comment]
thanks for your work. your changes sound good. you can publish, but I would hold off with tagging the `koa@2` version as `latest` until I (or someone else) publishes koa@2 this weekend.

let me know if u you need npm rights

**Comment by nervgh** [comment]
@jonathanong 

Next syntax implemented:
- [x] router.use() method
- [x] path & middleware both optional but it requires at least one of them

Tests and documentation updated.
All are inside of [next](https://github.com/koajs/trie-router/tree/next) branch.

---

> let me know if u you need npm rights

It would be good.

**Comment by jonathanong** [comment]
@nervgh what's your npm username?

**Comment by nervgh** [comment]
@jonathanong https://www.npmjs.com/~nerv

**Comment by jonathanong** [comment]
added!

**Comment by nervgh** [comment]
thank you :smile_cat:

**Comment by nervgh** [comment]
Done https://github.com/koajs/trie-router/releases/tag/2.1.0
