### ISSUE TITLE
Could you guys implement a function named "all" for this router

### ISSUE THREAD

**Issue by fengxinming** [koajs/trie-router#37]
I wonder why "router.all" wasn't defined, althought "router.addRoute('ANY', paths, middleware)" can be easy to be used, I still expect you guys to implement "router.all".

**Comment by nervgh** [comment]
Looks like `router.use()` is what you need.

https://github.com/koajs/trie-router#usage

**Comment by fengxinming** [comment]
@nervgh No, it's different from router.all, look at the following code
use(...middleware) {
  return this.addRoute('ANY', middleware)
}
[__ADD_ROUTE](method, paths, middleware) {
}

**Comment by nervgh** [comment]
@fengxinming What behavior do you need (expected)?

**Comment by fengxinming** [comment]
@nervgh I meant you are adding a function "router.all" that's like "router.get" or "router.post" but it can handle all of kinda http request, do you totally know what I mean?

**Comment by nervgh** [comment]
@fengxinming , 

> I meant you are adding a function "router.all" that's like "router.get" or "router.post" but it can handle all of kinda http request

`router.use()`  does these things. Did you try use `router.use()`?

**Comment by fengxinming** [comment]
@nervgh Okay! you're closing this issue, I've extended a function by myself, thanks!
