### ISSUE TITLE
fails to route OPTIONS

### ISSUE THREAD

**Issue by panva** [koajs/trie-router#40]
👋 I have an issue to report, looks like a bug to me but i find it weird noone else has figured this out. I might as well be doing something wrong.

Here goes, ... 

any `router.options(...)` route registered middleware is never ran, instead all OPTIONS requests seem to be handled by a fixed code.

This is an issue for when a specific cors preflight middleware needs to be mounted to a routes OPTIONS

wdyt?

**Comment by nervgh** [comment]
Thank you for reporting this issue :)

**Comment by nervgh** [comment]
The issue is solved by @alexghr :v:
